export const cuisineList = [
  { id: 1, name: "American" },
  { id: 2, name: "BBQ" },
  { id: 3, name: "Breakfast" },
  { id: 4, name: "Burgers" },
  { id: 5, name: "Cafe" },
  { id: 6, name: "Chinese" },
  { id: 7, name: "Desserts" },
  { id: 8, name: "French" },
  { id: 9, name: "Greek" },
  { id: 10, name: "Healthy" },
  { id: 11, name: "Indian" },
  { id: 12, name: "Italian" },
  { id: 13, name: "Japanese" },
  { id: 14, name: "Mexican" },
  { id: 15, name: "Noodles" },
  { id: 16, name: "Organic" },
  { id: 17, name: "Pasta" },
  { id: 18, name: "Pizza" },
  { id: 19, name: "Salads" },
  { id: 20, name: "Seafood" },
  { id: 21, name: "Spanish" },
  { id: 22, name: "Steak" },
  { id: 23, name: "Sushi" },
  { id: 24, name: "Tacos" },
  { id: 25, name: "Tapas" },
  { id: 26, name: "Vegan" },
];
